client:
  hosts:
    - ${SERVICE_ELASTICSEARCH_HOST}
  port: ${SERVICE_ELASTICSEARCH_PORT}
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  aws_key:
  aws_secret_key:
  aws_region:
  ssl_no_validate: False
  http_auth: ${ELASTICSEARCH_CREDENTIAL}
  timeout: 30
  master_only: False

logging:
  loglevel: ${SERVICE_CURATOR_LOGGING_LEVEL}
  logfile:
  logformat: json
  blacklist: ['elasticsearch', 'urllib3']
